# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
    tags:
      - v*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Git
      run: |
        git fetch --tags --unshallow origin
        git status
        echo Version:
        git describe --always

    - name: Setup Nim environment
      uses: jiro4989/setup-nim-action@v1.1.4
      with:
        # The Nim version to download (if necessary) and use. Example: 1.0.2
        nim-version: stable # optional, default is stable

    - name: Install toolchains
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt install gcc make gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu

    - name: Construct release name
      id: vars
      run: |
        if [[ "${GITHUB_REF#refs/tags/}" = "${GITHUB_REF#refs/*/}" ]]; then
          echo ::set-output name=prerelease::false
          echo ::set-output name=release_name::${GITHUB_REF#refs/*/}
        else
          echo ::set-output name=prerelease::true
          echo ::set-output name=release_name::latest-${GITHUB_REF#refs/*/}
          git push origin +HEAD:refs/tags/latest-${GITHUB_REF#refs/*/}
        fi

    - name: Build
      run: |
        set -x
        mkdir dist
        nimble install -d -y

        nimble c -d:ssl -d:version=$(git describe --always) src/accountserver
        cp src/accountserver dist/accountserver-`uname -m`-${{ steps.vars.outputs.release_name }}
        tar Jcf dist/accountserver-`uname -m`-${{ steps.vars.outputs.release_name }}.tar.xz -C src accountserver

        for arch in arm64; do
          git clean -fdx src
          nimble c --cpu:$arch -d:ssl -d:version=$(git describe --always) src/accountserver
          cp src/accountserver dist/accountserver-$arch-${{ steps.vars.outputs.release_name }}
          tar Jcf dist/accountserver-$arch-${{ steps.vars.outputs.release_name }}.tar.xz -C src accountserver
        done

    # https://github.com/marketplace/actions/create-release
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*"
        allowUpdates: true
        prerelease: ${{ fromJson(steps.vars.outputs.prerelease) }}
        tag: ${{ steps.vars.outputs.release_name }}
        token: ${{ secrets.GITHUB_TOKEN }}

